
// Auto-generated by AutoPilot on 28-07-2023 at 05:53:32


const express = require('express');
const router = express.Router();

//Stack Implementation
class Stack { 
    constructor() { 
        this.items = []; 
    } 
    push(element) { 
        this.items.push(element); 
    } 
    pop() { 
        if (this.items.length == 0) 
            return "Underflow"; 
        return this.items.pop(); 
    } 
    peek() { 
        return this.items[this.items.length - 1]; 
    } 
    isEmpty() { 
        return this.items.length == 0; 
    } 
    printStack() { 
        let str = ""; 
        for (let i = 0; i < this.items.length; i++) 
            str += this.items[i] + " "; 
        return str; 
    } 
} 

//Route to return stack
router.get('/stack', (req, res) => {
    const stack = new Stack();
    stack.push("Google"); 
    stack.push("Udemy"); 
    stack.push("Discord"); 
    let stackString = stack.printStack();
    res.send(stackString);
});

module.exports = router;