
// Auto-generated by AutoPilot on 28-07-2023 at 04:12:50

const express = require('express');
const router = express.Router();

//Router for sw API
router.get('/sw', (req, res) => {
    res.send('Pew pew pew'); //Send pew pew pew as response
});

module.exports = router; //Export router